version: '3.8'

services:
  dox-agent:
    build: .
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - TAVILY_API_KEY=${TAVILY_API_KEY}
      - LANGCHAIN_API_KEY=${LANGCHAIN_API_KEY}
      - LANGCHAIN_TRACING_V2=${LANGCHAIN_TRACING_V2}
      - LANGCHAIN_PROJECT=${LANGCHAIN_PROJECT}
      - MAX_ITERATIONS=${MAX_ITERATIONS}
      - MODEL_NAME=${MODEL_NAME}
      - MAX_RESULTS=${MAX_RESULTS}
    volumes:
      - ./results:/app/results 